# This pipeline builds the current project, make unit tests and then deploys to Github

# default:
  # image: ghcr.io/actions/jekyll-build-pages:v1.0.13

build-job:
  stage: build
  script:
    # - ls
    # Install Ruby Gems to ~/gems
    - export GEM_HOME=/usr/local/bin
    - export PATH=$GEM_HOME/bin:$PATH
    # - TMP_GIT_CLONE=$HOME/tmp/myrepo && GEMFILE=$TMP_GIT_CLONE/Gemfile && PUBLIC_WWW=/var/www/myrepo
    # - git clone $GIT_DIR $TMP_GIT_CLONE
    - bundle install
    - bundle exec jekyll build -s $HOME/tmp/myrepo -d /var/www/myrepo
    # - BUNDLE_GEMFILE=$GEMFILE bundle install
    # - BUNDLE_GEMFILE=$GEMFILE bundle exec jekyll build -s $TMP_GIT_CLONE -d $PUBLIC_WWW
    # - rm -Rf $TMP_GIT_CLONE
    # - jekyll build
    # exit 
  # variables:
    # source: .
    # destination: ./_site
    # verbose: true
  artifacts:
    paths:
      - /var/www/myrepo

deploy-prod:
  stage: deploy
  when: manual
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
  script:
    - git config user.email "taflilou@gmail.com"
    - git config user.name "abdel tessilimi"
    - git remote add github_origin https://taflilou:$GITHUB_TOKEN@github.com/taflilou/afrodiplomacy.github.io.git
    - git checkout main
    - git pull
    - git add .
    # - git commit --allow-empty -m "Deployment to production"
    # - git push --set-upstream github_origin main
    - git push -f github_origin main
  environment: production
