# This pipeline builds the current project, make unit tests and then deploys to Github

stages:
  - unit-test 

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "Hello, $GITHUB_TOKEN!"

unit-test:
  stage: unit tests
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 30

deploy-github:
  stage: Deploy to github
  script:
    - git config user.email "taflilou@gmail.com"
    - git config user.name "abdel tessilimi"
    - echo "Hello, $GITHUB_TOKEN!"
    - git remote set-url github_origin https:taflilou:$GITHUB_TOKEN//github.com/taflilou/afrodiplomacy.github.io.git
    - git add .
    - git commit -m "Deploy yo production"
    - git push gitlab_origin HEAD:main -o ci.skip
  environment: production
