title: afrodiplomacy
description: afrodiplomacy

url: https://taflilou.github.io
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10
full-width: true
class: wide

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: afrodiasporas
    twitter: afrodiasporas
    facebook: afrodiasporas
    email: afrodiasporas@gmail.com
    linkedin: afrodiasporas
    youtube: afrodiasporas
    tumblr: afrodiasporas

google_analytics: "UA-58263416-1"

disqus:
    shortname: afrodiasporas
